// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL_YhewyN4kS8OjnQCvGcWhrY_Qam0HLM',
    appId: '1:640456292588:web:bde7808f8be20ddeeb0dc9',
    messagingSenderId: '640456292588',
    projectId: 'pratcice-6330b',
    authDomain: 'pratcice-6330b.firebaseapp.com',
    storageBucket: 'pratcice-6330b.firebasestorage.app',
    measurementId: 'G-MM2LK29ME2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0mS85kQhI4YHuwapQNroF48nFYXPZeI',
    appId: '1:640456292588:android:c9a208bc70046063eb0dc9',
    messagingSenderId: '640456292588',
    projectId: 'pratcice-6330b',
    storageBucket: 'pratcice-6330b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1hFuz7ZH0VHBJAsdPlE_YiHnSao8wgro',
    appId: '1:640456292588:ios:c5187d0b3bb836b3eb0dc9',
    messagingSenderId: '640456292588',
    projectId: 'pratcice-6330b',
    storageBucket: 'pratcice-6330b.firebasestorage.app',
    iosBundleId: 'com.example.myapp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1hFuz7ZH0VHBJAsdPlE_YiHnSao8wgro',
    appId: '1:640456292588:ios:c5187d0b3bb836b3eb0dc9',
    messagingSenderId: '640456292588',
    projectId: 'pratcice-6330b',
    storageBucket: 'pratcice-6330b.firebasestorage.app',
    iosBundleId: 'com.example.myapp01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL_YhewyN4kS8OjnQCvGcWhrY_Qam0HLM',
    appId: '1:640456292588:web:736e423c3ef3486eeb0dc9',
    messagingSenderId: '640456292588',
    projectId: 'pratcice-6330b',
    authDomain: 'pratcice-6330b.firebaseapp.com',
    storageBucket: 'pratcice-6330b.firebasestorage.app',
    measurementId: 'G-YDBNE1S9BG',
  );
}
